browse/urls.py
from django.urls import path, re_path, include
from django.views.generic.base import TemplateView

from .views import *

urlpatterns = [
    path('', TemplateView.as_view(template_name='browse/intro.html')),
    re_path(r'returnables/?$', returnables_by_type),
    re_path(r'restrictables/?$', restrictables),
    re_path(r'requestables/?$', requestables),
    re_path(r'log/?$', log),
    re_path(r'check/?$', check),
    re_path(r'new/?$', makenew),
]

urls.py
from django.urls import path, include

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    path('', include('browse.urls')),
    path('admin/', admin.site.urls),
]

browse/models.py
from django.db import models

class Usage(models.Model):
    name = models.CharField(max_length=256)
    def __unicode__(self):
        return u'%s'%self.name

class KeyWord(models.Model):
    name = models.CharField(max_length=256,unique=True)
    sdescr = models.TextField('Short description')
    ldescr = models.TextField('Long description')
    type = models.CharField('Type',max_length=1, choices=( ('s','String'),
                                                    ('i','Integer'),
                                                    ('f','Float'),
                                                    ('b','Boolean'),
                                                  ),
                            null=True,blank=True)
    constr = models.CharField('Constraint',max_length=256,null=True,blank=True)
    unit = models.CharField('Unit',max_length=256,null=True,blank=True)
    usage = models.ManyToManyField(Usage,blank=True)
    block = models.CharField('XSAMS block',max_length=2, choices=( \
                                                    ('at','Atoms'),
                                                    ('as','Atomic States'),
                                                    ('mo','Molecules'),
                                                    ('ms','Molecular States'),
                                                    ('mq','Molecular Quantum Numbers'),
                                                    ('ct','Collisional Transitions'),
                                                    ('rt','Radiative Transitions'),
                                                    ('nr','Non-Radiative Transitions'),
                                                    ('me','Methods'),
                                                    ('fu','Functions'),
                                                    ('en','Environments'),
                                                    ('so','Sources'),
                                                    ('sd','Solids'),
                                                    ('pa','Particles'),
                                                  ),
                            null=True,blank=True)
    datatype = models.BooleanField('DataType in XSAMS?',default=False)

    def list_usages(self):
        return ', '.join([u.name for u in self.usage.all()])

    def __unicode__(self):
        return u'%s'%self.name

    class Meta:
        ordering = ["name"]
        verbose_name = 'Keyword'
        verbose_name_plural = 'Keywords'

browse/views.py
# Create your views here.
from django import forms
from django.shortcuts import render
from django.template import RequestContext
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.forms.models import modelformset_factory
#from django.forms.formsets import formset_factory
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.admin.models import LogEntry


from .models import Usage,KeyWord
RETURNA=Usage.objects.get(pk=2)
REQUESTA=Usage.objects.get(pk=3)
RESTRICTA=Usage.objects.get(pk=1)
RetQ = Q(usage=RETURNA)

import re
REGEX1=re.compile(r"""^\s*(RETURNABLES|RESTRICTABLES)\s*=\s*\{\s*\\?\s*(['"]\w+['"]\s*:\s*[ru]?['"][\w\-\\_\.,/()\[\]'"=\ ]*['"]\s*,?\s*)*\s*\}\s*$""")

REGEX2=re.compile(r"""^(Atom|AtomState|Source|Molecule|MoleculeState|CollTran|RadTran|Method|MoleQNs)\..*$""")

def log(request):
    logs = LogEntry.objects.all()
    return render(request,'browse/log.html',{'object_list':logs})

def restrictables(request):
    words = KeyWord.objects.filter(usage=RESTRICTA)
    return render(request,'browse/index.html',{'firstpara':'Restrictables','object_list':words})

def requestables(request):
    words = KeyWord.objects.filter(usage=REQUESTA)
    return render(request,'browse/index.html',{'firstpara':'Requestables','object_list':words})

def returnables_by_type(request):
    atoms = KeyWord.objects.filter(RetQ, block__in=('at','as'))
    atoms.desc = 'Atoms and atomic states'
    atoms.tag = 'at'
    molecs = KeyWord.objects.filter(RetQ, block__in=('mo','ms','mq'))
    molecs.desc = 'Molecules, their states and quantum numbers'
    molecs.tag = 'mo'
    solp= KeyWord.objects.filter(RetQ, block__in=('sd','pa'))
    solp.desc = 'Solids and Particles'
    solp.tag = 'sp'
    procs = KeyWord.objects.filter(RetQ, block__in=('rt','ct','nr'))
    procs.desc = 'Processes'
    procs.tag = 'pr'
    oth = KeyWord.objects.filter(RetQ, block__in=('en','fu','me','so'))
    oth.desc = 'Environments, Functions, Methods and Sources'
    oth.tag = 'oh'
    noxsams = KeyWord.objects.filter(RetQ, block=None)
    noxsams.desc = 'Unclassified Keywords'
    noxsams.tag = 'nx'
    blocs = [atoms, molecs, solp, procs, oth, noxsams]
    return render(request, 'browse/bytype.html', {'blocs': blocs})

def bareKW(kw):
    kw = kw.lower()
    suffixes=['unit','ref','comment','accuracy','method']
    for suff in suffixes:
        if kw.endswith(suff):
            return kw.rsplit(suff,1)[0]

def check_keyword_exists(kw):
    try: KeyWord.objects.get(name__iexact=kw)
    except KeyWord.DoesNotExist:
        barekw = bareKW(kw)
        if not barekw:
            return 'Keyword %s does not exist in the dictionary.'%kw

        try: k = KeyWord.objects.get(name__iexact=barekw)
        except KeyWord.DoesNotExist:
            return 'Keyword %s does not exist in the dictionary. (It is used with one of the DataType suffixes)'%barekw
        if not k.datatype:
            return 'Your used keyword %s with a DataType suffix but it is not a DataType.'%barekw

def check_keyword_usage(kw,usage):
    try: kw = KeyWord.objects.get(name__iexact=kw)
    except: return
    if not usage in kw.usage.all():
        return '%s is not a %s according to the dictionary.'%(kw,usage.name)

def check_returnvalues(kw,value):
    if not REGEX2.match(value):
        return 'The value "%s" of %s does not start with one of the known prefixes. This is fine, if you intend to return this as a constant string.'%(value,kw)

def check_unit(kw,keys):
    try: k = KeyWord.objects.get(name__iexact=kw)
    except: return
    if k.datatype:
        keys = map(str.lower,keys)
        if not kw.lower() + 'unit' in keys:
            return 'You use the DataType %s but not the corresponding keyword for its unit (%sUnit).'%(kw,kw)

def validate_dict(data):
    errors=[]
    if not REGEX1.match(data):
        errors.append('First syntax check did not pass. (Comments with # are not allowed in this check.)')

    name,value = data.split('=')
    name=str.strip(name)
    if name == 'RETURNABLES': usage = RETURNA
    elif name == 'RESTRICTABLES': usage = RESTRICTA
    else: errors.append('Neither RETURNABLES or RESTRICTABLES assignment found')
    value = ''.join(map(str.strip,map(strip,value.splitlines()),'\\'))
    try: value=eval(value)
    except:
        errors.append('Second check (evalution) did not pass. Please check that your input is correct Python code.')
        raise ValidationError(errors)

    for kw in value.keys():
        err = check_keyword_exists(kw)
        if err:
            errors.append(err)
            continue
        err = check_keyword_usage(kw,usage)
        if err: errors.append(err)
        if usage==RETURNA:
            err = check_returnvalues(kw,value[kw])
            if err: errors.append(err)
            err = check_unit(kw,value.keys())
            if err: errors.append(err)
    if errors: raise ValidationError(errors)

class CheckForm(forms.Form):
    content=forms.CharField(label='Paste your dictionary',
    widget=forms.widgets.Textarea(attrs={'cols':'80','rows':'25'}),
    required=True,validators=[validate_dict])

def check(request):
    if request.method == 'POST':
        form = CheckForm(request.POST)
        if form.is_valid():
            #print form.cleaned_data
            pass

    else:
        form=CheckForm()
    return render(request, 'browse/check.html', {'form': form})


#########
blockmap = {'so':'Source.',
'as':'AtomState.',
'ms':'MoleculeState.',
'mq':'MoleQNs.',
'ct':'CollTran.',
'rt':'RadTran.',
'me':'Method.',
'mo':'Molecule.',
'at':'AtomState.',
}

def makedicts(selected):
    content = 'RETURNABLES = {\ \n'
    for kw in selected:
        if RETURNA in kw.usage.iterator():
            if blockmap.has_key(kw.block): prefix=blockmap[kw.block]
            else: prefix=''
            content += '\'%s\':\'%s\',\n'%(kw.name,prefix)

    content += '}\n\n\n'
    content += 'RESTRICTABLES = {\ \n'
    for kw in selected:
        if RESTRICTA in kw.usage.iterator():
            content += '\'%s\':\'\',\n'%kw.name

    content += '}\n\n\n'
    return content

class SelectKeyWordFormSet(forms.models.BaseModelFormSet):
    def add_fields(self, form, index):
        super(SelectKeyWordFormSet, self).add_fields(form, index)
        form.fields["include"] = forms.BooleanField(required=False, label="Include this keyword")


def makenew(request):
    q = Q(usage=RESTRICTA) | Q(usage=RETURNA)
    queryset = KeyWord.objects.filter(q).distinct()
    MakeNewFormSet = modelformset_factory(KeyWord,formset=SelectKeyWordFormSet,extra=0)

    if request.method == 'POST':
        formset = MakeNewFormSet(request.POST,request.FILES,queryset=queryset)
        if formset.is_valid():
            selected=[]
            for form in formset.cleaned_data:
                if form['include']: selected.append(form['id'])

            filecontent = makedicts(selected)
            response=HttpResponse(filecontent,mimetype='text/x-python')
            response['Content-Disposition'] = 'attachment; filename=dictionaries.py'
            return response

    else:
        formset = MakeNewFormSet(queryset=queryset)

    return render(request, 'browse/makenew.html', {'formset': formset})

browse/templates/browse/bytype.html
{% extends "browse/index.html" %}

{% block addheader %}
<script language="javascript">
  function toggleDiv(divid){
      if(document.getElementById(divid).style.display == 'none'){
         document.getElementById(divid).style.display = 'block';
  }else{
         document.getElementById(divid).style.display = 'none'
}}
</script>
{% endblock %}

{% block content %}

<p>Returnables</p>

{% for bloc in blocs %}
<h3>{{ bloc.desc }}</h3>
<div id="block{{ bloc.tag}}" style="display:none">
<p><a href="javascript:;" onmousedown="toggleDiv('block{{ bloc.tag }}');">Show/Hide</a></p>
<table>
<tr><th>Keyword</th><th>Short Description</th><th>Long Description</th><th>Type</th><th>*</th></tr>
{% for keyword in bloc %}
<tr class="{% cycle 'row1' 'row2' %}">
<td>{{ keyword.name }}</td>
<td>{{ keyword.sdescr }}</td>
<td>{{ keyword.ldescr }}</td>
<td>{% if keyword.type %}{{ keyword.get_type_display }}{% endif %}</td>
<td>{% if keyword.datatype %}*{% endif %}</td>
{% endfor %}
</table>
</div>
<p><a href="javascript:;" onmousedown="toggleDiv('block{{ bloc.tag }}');">Show/Hide</a></p>
{% endfor %}

{% endblock %}


{% block content2 %}

<p>
<a name="descr"></a>Description of the columns in the table above:
</p>

<ul>
<li><strong>Keyword</strong>: The actual name of the dictionary entry. These are what is used in the query language and when you fill Restrictables and Returnables.</li>
<li><strong>Short Description</strong>: Human-readable short text about the meaning. To be used e.g. as label text for a web-form</li>
<li><strong>Long Description</strong>: Human-readable longer text, to be used eg. in a help-box.</li>
<li><strong>Type</strong>: What type of data are associated with the keyword. choices are: string, float, integer, boolean.</li>

<li><strong>*</strong>: This column marks if a keyword corresponds to a
"DataType" in the XSAMS schema. If SomeKeyword is marked here, it means that
also the following keywords can be used
<ul>
<li>SomeKeywordUnit</li>
<li>SomeKeywordRef</li>
<li>SomeKeywordComment</li>
<li>SomeKeywordMethod</li>
<li>SomeKeywordAccuracy</li>
<li>SomeKeywordAccuracyConfidence</li>
<li>SomeKeywordAccuracyRelative</li>
<li>SomeKeywordAccuracyType</li>
<li>SomeKeywordEval</li>
<li>SomeKeywordEvalMethod</li>
<li>SomeKeywordEvalRecommended</li>
<li>SomeKeywordEvalRef</li>
<li>SomeKeywordEvalComment</li>
</ul> which for the sake of overview are not listed for each keyword above. Please refer to the schema documentation on how these are to be filled.</li>

</ul>
</p>
{% endblock %}

browse/templates/browse/check.html
{% extends "indigo.html" %}
{% load i18n %}

{% block content %}
<h1>Check your dictionaries</h1>

<p>Paste your dictionary into the field 
below, including the variable assignment. Examples and more information below.</p>

<form action="." method="post">
{% csrf_token %}
<p>{{ form.content }}</p>
<p><input type="submit" value="Check" /></p>

{% if form.content.errors %}
<p>Check result:</p>
{{ form.content.errors }}
{% else %}
<p>No errors found.</p>
{% endif %}
</form>

<h2>Examples</h2>

<p>
<code>
RETURNABLES = {'AtomSymbol':'AtomState.species.name',
'AtomIonCharge':'AtomState.species.ion',
'RadTransWavelength':'RadTran.vacwave',
'RadTransWavelengthUnit':'cm',
}
</code>
</p>

<p>
<code>
RESTRICTABLES = {'AtomSymbol':'species__name',
'AtomNuclearCharge':'species__atomic',
'RadTransWavelength':'vacwave'
}
</code>
</p>

<p>This tool warns you of
<ul>
<li>syntax errors</li>
<li>keywords you use which are not in the dictionary</li>
<li>keywords that cannot be used as Returnable or Restrictable as you do</li>
<li>values (right-hand-side) which probably will not be replaced by something from your database but treated as constant strings instead.</li>
<li>forgetting the Unit-keyword when you fill a DataType.</li>
</ul>
</p>
<p>This tool <strong>does not</strong> check whether the values you put into the right-hand-side match your data model or not.
</p>
{% endblock %}

browse/templates/browse/index.html
{% extends "indigo.html" %}
{% block title %}VAMDC{% endblock %}

{% block headline %}VAMDC Dictionary{% endblock %}

{% block content %}
<p>{{ firstpara }}</p>

<table>
<tr><th>Keyword</th><th>Short Description</th><th>Long Description</th><th>Type</th><th>Constraint</th><th>Unit</th></tr>
{% for keyword in object_list %}
<tr class="{% cycle 'row1' 'row2' %}">
<td>{{ keyword.name }}</td>
<td>{{ keyword.sdescr }}</td>
<td>{{ keyword.ldescr }}</td>
<td>{% if keyword.type %}{{ keyword.get_type_display }}{% endif %}</td>
<td>{% if keyword.constr %}{{ keyword.constr }}{% endif %}</td>
<td>{% if keyword.unit %}{{ keyword.unit }}{% endif %}</td>
{% endfor %}
</table>
<p/>
{% endblock %}

{% block content2 %}
<p>
<a name="descr"></a>Description of the columns in the table above:
</p>

<ul>
<li><strong>Keyword</strong>: The actual name of the dictionary entry. These are what is used in the query language and when you fill Restrictables and Returnables.</li>
<li><strong>Short Description</strong>: Human-readable short text about the meaning. To be used e.g. as label text for a web-form</li>
<li><strong>Long Description</strong>: Human-readable longer text, to be used eg. in a help-box.</li>
<li><strong>Type</strong>: What type of data are associated with the keyword. choices are: string, float, integer, boolean.</li>
<li><strong>Constraint</strong>: Possible contraints on the content, like ranges for a number, only certain strings (regular expression) etc.</li>
<li><strong>Unit</strong>: The default unit, if any, for the keyword. This unit is the one used at query-time. You may however use another unit when returning data.</li>
</ul>
</p>
{% endblock %}

browse/templates/browse/intro.html
{% extends "browse/index.html" %}
{% block content %}
<p>This is the VAMDC dictionary of keywords. Please see the <a href="http://vamdc.eu/documents/standards/">Standards documentation</a> for background information.</p>
<p>
<ul>
<li><a href="restrictables/">Restrictables</a> are the keywords that can be used in queries to VAMDC data nodes.</li>
<li><a href="requestables/">Requestables</a> can be used to limit the type of data that a query returns.</li>
<li><a href="returnables/">Returnables</a> are used internally by data nodes map data to the VAMDC data model.</li>
</ul>
</p>

{% endblock %}
{% block content2 %}{% endblock %}

browse/templates/browse/log.html
{% extends "indigo.html" %}
{% load i18n %}
{% block title %}VAMDC{% endblock %}

{% block headline %}VAMDC Dictionary Change Log{% endblock %}

{% block content %}

<p>Note that the list below only contains the changes made through the <a
href="/admin/">admin interface</a>, not direct changes in the
database.</p>

<table>
<tr><th>When?</th><th>Who?</th><th>What was changed?</th><th>How?</th></tr>
{% for logentr in object_list %}

<tr class="{% cycle 'row1' 'row2' %}">
<td>{{ logentr.action_time }}</td>
<td>{{ logentr.user.get_full_name }}</td>
<td>{{ logentr.content_type.name }}: {{ logentr.object_repr }}</td>
<td>
{% if logentr.is_addition %}Addition {% endif %}
{% if logentr.is_deletion %}Deletion {% endif %}
{{ logentr.change_message }}</td>

{% endfor %}
</table>

{% endblock %}

browse/templates/browse/makenew.html
{% extends "indigo.html" %}
{% load i18n %}

{% block content %}
<h1>Make new RETURNABLES and RESTRICTABLES</h1>

<p>Below you can mark all the keywords that correspond to your data. When you press "submit", a file will be generated and downloaded to you that contains a first guess (you will have to edit it!) for <em>dictionaries.py</em> in your node.</p>

<form action="." method="post">
{% csrf_token %} 
{{ formset.management_form }}
<table>
  <tr><th>Use?</th><th>Keyword</th><th>Description</th></tr>
{% for form in formset.forms %}
<tr><td>{{ form.include }}{{ form.id }}
{{ form.name.as_hidden }}
{{ form.sdescr.as_hidden }}
{{ form.ldescr.as_hidden }}
</td><td>{{ form.instance.name }}</td><td>{{ form.instance.ldescr }}</td></tr>
{% endfor %}
</table>
<p/>
<p><input type="submit" value="Submit and download file" /></p>
<p/>
<p/>

</form>


{% endblock %}